// Code generated by hero.
// source: /home/matt/go/src/github.com/mattsykesj/hello/views/addFood.html
// DO NOT EDIT!
package template

import (
	"io"

	"github.com/shiyanhui/hero"
)

func RenderAddFood(title string, addedFood string, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<base href="../">
    <title>`)
	hero.EscapeHTML(title, _buffer)
	_buffer.WriteString(`</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="/content/css/site.css">
	<script type="text/javascript" src="/content/scripts/validate.js"></script>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
</head>
<body>

 `)
	_buffer.WriteString(`

<form id="food-form" method="POST" class="p-4" style="max-width: 50%">
	<h2 class="pb-2">Add Food</h2>
	<div class="row form-group" id="name-div">
		<label class="col-2 col-form-label pr-0" for="name">Name</label>
		<div class="col-6">
			<input type="text" class="form-control" name="name" id="name">
			<small class="validation-text" name="name-val-div"></small>
		</div>
		<div class="col-4 p-0">
			<i class="fa fa-thumbs-up my-2 success-text" name="name-svg-success" style="display:none"></i>
			<i class="fa fa fa-thumbs-down my-2 validation-text" name="name-svg-error" style="display:none"></i>
		</div>
	</div>
	<div class="row form-group" id="calories-div">
		<label class="col-2 col-form-label pr-0" for="calories">Calories</label>
		<div class="col-6">
			<input type="text" class="form-control" name="calories" id="calories">
			<small class="validation-text" name="calories-val-div"></small>
		</div>
		<div class="col-4 p-0">
			<i class="fa fa-thumbs-up my-2 success-text" name="calories-svg-success" style="display:none"></i>
			<i class="fa fa fa-thumbs-down my-2 validation-text" name="calories-svg-error" style="display:none"></i>
		</div>
	</div>
	<div class="row form-group" id="protein-div">
		<label class="col-2 col-form-label pr-0" for="protein">Protein</label>
		<div class="col-6">
			<input type="text" class="form-control" name="protein" id="protein">
			<small class="validation-text" name="protein-val-div"></small>
		</div>
		<div class="col-4 p-0">
			<i class="fa fa-thumbs-up my-2 success-text" name="protein-svg-success" style="display:none"></i>
			<i class="fa fa fa-thumbs-down my-2 validation-text" name="protein-svg-error" style="display:none"></i>
		</div>
	</div>
	<div class="row form-group" id="carbohydrate-div">
		<label class="col-2 col-form-label pr-0" for="carbohydrate">Carbohydrate</label>
		<div class="col-6">
			<input type="text" class="form-control" name="carbohydrate" id="carbohydrate">
			<small class="validation-text" name="carbohydrate-val-div"></small>
		</div>
		<div class="col-4 p-0">
			<i class="fa fa-thumbs-up my-2 success-text" name="carbohydrate-svg-success" style="display:none"></i>
			<i class="fa fa fa-thumbs-down my-2 validation-text" name="carbohydrate-svg-error" style="display:none"></i>
		</div>
	</div>
	<div class="row form-group" id="fat-div">
		<label class="col-2 col-form-label pr-0" for="fat">Fat</label>
		<div class="col-6">
			<input type="text" class="form-control" name="fat" id="fat">
			<small class="validation-text" name="fat-val-div"></small>
		</div>
		<div class="col-4 p-0">
			<i class="fa fa-thumbs-up my-2 success-text" name="fat-svg-success" style="display:none"></i>
			<i class="fa fa fa-thumbs-down my-2 validation-text" name="fat-svg-error" style="display:none"></i>
		</div>
	</div>

	<input type="submit" class="btn btn-primary" id="food-submit" value="Add">
	<a href="/food/"><input type="button" class="btn btn-default" value="Back"></a>

</form>

`)
	if len(addedFood) > 0 {
		_buffer.WriteString(` 
	<div>
		<h4 class="success success-text">Added `)
		_buffer.WriteString(addedFood)
		_buffer.WriteString(`!</h4>
	</div>
`)
	}
	_buffer.WriteString(`

<script type="text/javascript">

$(document).ready(function(){
	$('#food-form').submit(function(){
		return validateFood();
	});
});

</script>

`)

	_buffer.WriteString(`

</body>
</html>`)
	w.Write(_buffer.Bytes())

}
