// Code generated by hero.
// source: /home/matt/go/src/github.com/mattsykesj/hello/views/login.html
// DO NOT EDIT!
package template

import (
	"io"

	"github.com/shiyanhui/hero"
)

func RenderLogin(title string, loginError bool, w io.Writer) {
	_buffer := hero.GetBuffer()
	defer hero.PutBuffer(_buffer)
	_buffer.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<base href="../">
    <title>`)
	hero.EscapeHTML(title, _buffer)
	_buffer.WriteString(`</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="/content/css/site.css">
	<script type="text/javascript" src="/content/scripts/validate.js"></script>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	<script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
</head>
<body>

 `)
	_buffer.WriteString(`

<div class="d-flex flex-column">
	<div class="p-2 justify-content-center">
		<h2>Log in</h2>
		<form method="POST">
			<div class="row form-group" id="username-div">
				<label class="col-2 col-form-label pr-0" for="username">User Name</label>
				<div class="col-6">
					`)
	if loginError == true {
		_buffer.WriteString(` 
						<input type="text" class="form-control error" name="username" id="username">
					`)
	} else {
		_buffer.WriteString(`
						<input type="text" class="form-control" name="username" id="username">
					`)
	}
	if loginError == true {
		_buffer.WriteString(` 
						<small class="validation-text" name="username-val-div">Username not found</small>
					`)
	}
	_buffer.WriteString(`
				</div>
				<div class="col-4 p-0">
					`)
	if loginError == true {
		_buffer.WriteString(` 
						<i class="fa fa fa-thumbs-down my-2 validation-text" name="username-svg-error"></i>
					`)
	}
	_buffer.WriteString(`
				</div>
			</div>
		</form>
	</div>
</div>

`)

	_buffer.WriteString(`

</body>
</html>`)
	w.Write(_buffer.Bytes())

}
